[settings]
# Core settings
experimental = true
all_compile = false
activate_aggressive = true
env_shell_expand = true

# UI/UX
color_theme = "catppuccin"

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[tools]
# --- CLI Tools ---
# This exists so that my key workflow is system agnostic
fzf = "latest"
fd = "latest"
ripgrep = "latest"
ripgrep-all = "latest"
eza = "latest"
bat = "latest"
bat-extras = "latest"
zoxide = "latest"
yazi = "latest"
github-cli = "latest"
xh = "latest"
delta = "latest"
"cargo:tealdeer" = "latest"
sd = "latest"
atuin = "latest"
"pipx:visidata" = { version = "latest", extras = ["full"] }
duckdb = "latest"
navi = "latest"
usage = "latest"
"cargo:ouch" = "latest"

# --- Core Runtimes ---
node = "latest"
bun = "latest"
zig = "latest"
watchexec = "latest"
luajit = "latest"

# --- Language Servers (LSP) ---
lua-language-server = "latest"                     # Lua
"npm:bash-language-server" = "latest"              # Bash
"npm:pyright" = "latest"                           # Python
"npm:vscode-json-languageserver" = "latest"        # JSON
"npm:yaml-language-server" = "latest"              # YAML
"npm:dockerfile-language-server-nodejs" = "latest" # Docker

# --- Linters & Formatters ---
# General & Parsing
tree-sitter = "latest" # Incremental parsing library
ty = "latest"          # Typo checker (alternative)
typos = "latest"       # Source code spell checker

# Lua
lua = "latest"
stylua = "latest"
"cargo:selene" = "latest"

# Python
ruff = "latest"

# Shell (Bash/Fish)
shellcheck = "latest"
shfmt = "latest"

# JS/TS (Rust-powered tools)
oxlint = "latest"
oxfmt = "latest"

# Config Files
taplo = "latest"                             # TOML
yamllint = "latest"                          # YAML
"npm:vscode-json-languageservice" = "latest" # JSON

# --- Graphics & Typesetting ---
"npm:@mermaid-js/mermaid-cli" = "latest" # Diagrams
"cargo:tectonic" = "latest"              # LaTeX engine
"github:can1357/oh-my-pi" = "latest"
