%YAML 1.1
---
git:
  diffRenderers:
  - command: delta --dark --paging=never --line-numbers --hyperlinks 
      --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  authorColors:
    '*': '#b4befe'
  theme:
    activeBorderColor:
    - '#89b4fa'
    - bold
    cherryPickedCommitBgColor:
    - '#45475a'
    cherryPickedCommitFgColor:
    - '#89b4fa'
    defaultFgColor:
    - '#cdd6f4'
    inactiveBorderColor:
    - '#a6adc8'
    inactiveViewSelectedLineBgColor:
    - '#6c7086'
    markedBaseCommitBgColor:
    - '#f9e2af'
    markedBaseCommitFgColor:
    - '#89b4fa'
    optionsTextColor:
    - '#89b4fa'
    searchingActiveBorderColor:
    - '#f9e2af'
    selectedLineBgColor:
    - '#313244'
    unstagedChangesColor:
    - '#f38ba8'
