modelRoles:
  default: openrouter/deepseek/deepseek-v4-flash-0731:max
  advisor: openrouter/z-ai/glm-5.3-flash:high
  plan: google-antigravity/gemini-3.1-pro:high
  smol: google-antigravity/gemini-3.7-flash:medium
  slow: google-antigravity/gemini-3.1-pro:high
  vision: google-antigravity/gemini-3.7-flash
  designer: google-antigravity/gemini-3.7-flash:high
  commit: google-antigravity/tab_flash_lite_preview
  tiny: google-antigravity/tab_flash_lite_preview
  task: openrouter/deepseek/deepseek-v4-flash-0731:low
symbolPreset: nerd
theme:
  dark: titanium
  light: light
setupVersion: 2
composer:
  shape: box